In [13]:
import numpy as np
import tensorflow as tf
import gym
import scipy.signal
import os
import time
import inspect
from multiprocessing import Process

In [14]:
def build_mlp(
        input_placeholder,
        output_size,
        scope,
        n_layers=2,
        size=64,
        activation=tf.tanh,
        output_activation=None
        ):
    #========================================================================================#
    #                           ----------SECTION 3----------
    # Network building
    #
    # Your code should make a feedforward neural network (also called a multilayer perceptron)
    # with 'n_layers' hidden layers of size 'size' units.
    #
    # The output layer should have size 'output_size' and activation 'output_activation'.
    #
    # Hint: use tf.layers.dense
    #========================================================================================#

    with tf.variable_scope(scope,reuse=True):
        # YOUR_CODE_HERE
        out=input_placeholder
        for i in range(n_layers):
            if i==0:
                out=tf.layers.dense(inputs=input_placeholder, units=size, activation=activation)
            elif i==n_layers-1:
                out=tf.layers.dense(inputs=out,units=output_size,activation=output_activation)
            else:
                out=tf.layers.dense(inputs=out,units=size,activation=activation)

        return out

In [15]:
input_nn = tf.placeholder(shape=[None, 3], name="test", dtype=tf.float32)


In [16]:
x=build_mlp(input_nn,13,"base_nn3",2,64,tf.tanh)

ValueError: Variable base_nn3/dense/kernel does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=tf.AUTO_REUSE in VarScope?

In [ ]:
x.shape.dims

In [ ]:
input_nn.shape.dims

In [ ]:
sess = tf.InteractiveSession()

In [5]:
a=tf.log([[100., 100.]])
print(a.eval())
b=tf.constant([[100, 100., 100]])
print(b.eval())
print (a.shape)
print(b.shape)
c=np.array([[2,2]])
print(c.shape)

ValueError: Cannot evaluate tensor using `eval()`: No default session is registered. Use `with sess.as_default()` or pass an explicit session to `eval(session=sess)`

In [6]:
samples = tf.multinomial(b, 5)
print (samples.eval())
print(samples.shape)

NameError: name 'b' is not defined

In [7]:
sy_ob_no = tf.placeholder(shape=[None, 3], name="ob", dtype=tf.float32)
print(sy_ob_no.shape[0])

?


In [8]:
z=tf.constant([2, 1],shape=[1,2])
print(z.eval())
s=tf.constant([2,2], shape=[2,1])
print(s.eval())
h=tf.matmul(s,z)
print(h.eval())

ValueError: Cannot evaluate tensor using `eval()`: No default session is registered. Use `with sess.as_default()` or pass an explicit session to `eval(session=sess)`

In [9]:
s=tf.random_normal(z)
print(s.eval())

ValueError: Shape must be rank 1 but is rank 2 for 'random_normal/RandomStandardNormal' (op: 'RandomStandardNormal') with input shapes: [1,2].

In [78]:
a=tf.reduce_mean(s)
print(a.eval())

2


In [79]:
rew=np.array([1,2,3])
a=[]
for s in rew:
    a.append(s)
    print(s)
    
print(a)
print(a.reverse())

1
2
3
[1, 2, 3]
None


In [80]:
a=1
print(pow(a,2))

1


In [81]:
x = tf.constant([[1., 1.], [2., 2.]])
z=tf.reduce_mean(sy_ob_no)  # 1.5

In [82]:
sess.run(z, feed_dict={sy_ob_no: [[1,1,1]]})

1.0

In [83]:
a=np.array([1,2,3])

In [84]:
s=np.mean(a)

In [85]:
b=a-s

In [86]:
print(b)

[-1.  0.  1.]


In [87]:
sigma=np.std(a)

In [88]:
b=(a-s)/sigma

In [89]:
print(b)

[-1.22474487  0.          1.22474487]


In [90]:
print(sigma)

0.816496580927726


In [91]:
a=np.ones(5)
a.shape

(5,)

In [97]:
sy_mean = build_mlp(sy_ob_no, 2, "PG_C", n_layers=3, size=10)
sy_logstd = tf.Variable(tf.zeros([1,2]), name="logstd", dtype='float', trainable=True) # logstd should just be a trainable variable, not a network output.
sy_std = tf.exp(sy_logstd)

z = tf.random_normal(tf.constant([2,1]))
sy_sampled_ac=tf.matmul(sy_std, z)+sy_mean
sy_sampled_ac=tf.reshape(sy_sampled_ac,[-1])
sy_ac_na = tf.placeholder(shape=[None, 2], name="ac", dtype=tf.float32)


In [100]:
sqrt_sigma= tf.diag(sy_logstd)
sess.run(sqrt_sigma, feed_dict={sy_logstd:np.ones((1,2))})

array([[[[1., 0.]],

        [[0., 1.]]]], dtype=float32)

In [106]:
x=sy_mean-sy_ac_na
x.shape.dims
sy_mean.shape.dims

[Dimension(None), Dimension(2)]

In [107]:
z =  x/sy_std # Hint: Use the log probability under a multivariate gaussian
sy_logprob_n = 0.5*tf.norm(z)